version: "3.8"

services:
  # SQL Server service
  mssql2:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql2-db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "@Huy12345"
    ports:
      - "1434:1433"
    volumes:
      - ./.containers/mssql2:/var/opt/mssql/data
      - ./bk:/var/opt/mssql2/backup

  # SalesWebMvc service
  saleswebmvc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saleswebmvc-container
    ports:
      - "8089:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__SalesWebMvcContext: "Server=mssql2;Database=saleswebmvcappdb;User Id=sa;Password=@Huy12345;TrustServerCertificate=True;"
    depends_on:
      - mssql2
    restart: always

  saleswebapi:
    build:
      context: .
      dockerfile: Dockerfile.webapi
    container_name: saleswebapi-container
    ports:
      - "8090:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__SalesWebMvcContext: "Server=mssql2;Database=saleswebmvcappdb;User Id=sa;Password=@Huy12345;TrustServerCertificate=True;"
    depends_on:
      - mssql2
    restart: always

networks:
  saleswebnetwork:
    driver: bridge
